services:

  blog.infra.database:
    container_name: blog_database
    image: postgres:16

    environment:
      POSTGRES_DB: blog_database
      POSTGRES_USER: montgomery
      POSTGRES_PASSWORD: Teste@123
    ports:
      - "59595:5432"
    restart: unless-stopped